name: Update Schedule

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Allow manual run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main # FORCE it to check out the main branch

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - run: pip install -r requirements.txt
      
      - run: python scraper.py
      
      # THIS PLUGIN FIXES YOUR ERROR AUTOMATICALLY
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update schedule
          branch: main
          file_pattern: timetable.json
